import pytest

from src.vacancy import Vacancy


@pytest.fixture
def first_vacancy():
    return Vacancy(
        "116455408",
        "Python-разработчик",
        "Москва",
        {"from": 80000, "to": 105000, "currency": "RUR"},
        "https://hh.ru/vacancy/116455408",
        "От 1 года коммерческой разработки. Умение структурно мыслить, разбивать проект. Создание мониторингов",
    )


@pytest.fixture
def second_vacancy():
    return Vacancy(
        "116380094",
        "Сторож (вахтер)",
        "Ярославль",
        {"from": 25000, "to": None, "currency": "RUR"},
        "https://hh.ru/vacancy/116380094",
        "Без предъявления требований к квалификации.\n1. Контроль выноса материальных ценностей из...",
    )


@pytest.fixture
def third_vacancy():
    return Vacancy(
        "116451181",
        "Junior Java-разработчик",
        "Москва",
        None,
        "https://hh.ru/vacancy/116451181",
        "Умение быстро разбираться в коде Java (Spring). Хорошее знание SQL.",
    )


@pytest.fixture
def vacancies_list():
    vacancy1 = Vacancy(
        "116502539",
        "Инженер-конструктор",
        "Москва",
        {"from": 180000, "to": 0, "currency": "RUR"},
        "https://hh.ru/vacancy/116502539",
        "Работает в SolidWorks, AutoCAD (Компас как плюс). Составлял конструкторскую документацию",
    )
    vacancy2 = Vacancy(
        "116314492",
        "Инженер-конструктор (3/2 категории)",
        "Москва",
        {"from": 160000, "to": 180000, "currency": "RUR"},
        "https://hh.ru/vacancy/116314492",
        "Высшее техническое образование (бакалавр, магистр). Творческий подход к работе.",
    )
    vacancy3 = Vacancy(
        "116131587",
        "Чертежник AutoCAD",
        "Тула",
        {"from": 0, "to": 0, "currency": ""},
        "https://hh.ru/vacancy/116131587",
        "Опыт работы в AutoCAD. Умение работать с документами в Яндекс Диск.",
    )
    vacancy4 = Vacancy(
        "106268647",
        "Ученик оператора станков с ЧПУ",
        "Санкт-Петербург",
        {"from": 60000, "to": 200000, "currency": "RUR"},
        "https://hh.ru/vacancy/106268647",
        "ВАЖНО: отличные знания математики и геометрии. Образование средне-профессиональное / высшее",
    )
    vacancy5 = Vacancy(
        "116390705",
        "Инженер-конструктор (Обратное проектирование)",
        "Москва",
        {"from": 140000, "to": 0, "currency": "RUR"},
        "https://hh.ru/vacancy/116390705",
        "Опыт подготовки конструкторской документации согласно требований ЕСКД.",
    )
    return [vacancy1, vacancy2, vacancy3, vacancy4, vacancy5]


@pytest.fixture
def response_hh():
    return {
        "items": [
            {
                "id": "115804650",
                "premium": False,
                "name": "Специалист по подбору пары (Мачмейкер)",
                "department": None,
                "has_test": True,
                "response_letter_required": False,
                "area": {"id": "87", "name": "Тамбов", "url": "https://api.hh.ru/areas/87"},
                "salary": {"from": 30000, "to": 60000, "currency": "RUR", "gross": False},
                "type": {"id": "open", "name": "Открытая"},
                "address": {
                    "city": "Москва",
                    "street": "проспект Мира",
                    "building": "104",
                    "lat": 55.80238738046985,
                    "lng": 37.636828898147044,
                    "description": None,
                    "raw": "Москва, проспект Мира, 104",
                    "metro": None,
                    "metro_stations": [],
                    "id": "3481661",
                },
                "response_url": None,
                "sort_point_distance": None,
                "published_at": "2025-01-27T00:43:33+0300",
                "created_at": "2025-01-27T00:43:33+0300",
                "archived": False,
                "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=115804650",
                "show_logo_in_search": None,
                "insider_interview": None,
                "url": "https://api.hh.ru/vacancies/115804650?host=hh.ru",
                "alternate_url": "https://hh.ru/vacancy/115804650",
                "relations": [],
                "employer": {
                    "id": "4463078",
                    "name": "Успех",
                    "url": "https://api.hh.ru/employers/4463078",
                    "alternate_url": "https://hh.ru/employer/4463078",
                    "logo_urls": {
                        "90": "https://img.hhcdn.ru/employer-logo/3285080.png",
                        "240": "https://img.hhcdn.ru/employer-logo/3285081.png",
                        "original": "https://img.hhcdn.ru/employer-logo-original/710991.png",
                    },
                    "vacancies_url": "https://api.hh.ru/vacancies?employer_id=4463078",
                    "accredited_it_employer": False,
                    "trusted": True,
                },
                "snippet": {
                    "requirement": "Идеальные сочетания: Анализируй анкеты и создавай пары, основываясь на глубоком..",
                    "responsibility": "Создавай магию: Погружайся в мир наших клиентов — выясняй их мечты, интересы..",
                },
                "contacts": None,
                "schedule": {"id": "remote", "name": "Удаленная работа"},
                "working_days": [],
                "working_time_intervals": [],
                "working_time_modes": [],
                "accept_temporary": False,
                "fly_in_fly_out_duration": [],
                "work_format": [{"id": "REMOTE", "name": "Удалённо"}],
                "working_hours": [{"id": "OTHER", "name": "Другое"}],
                "work_schedule_by_days": [{"id": "FLEXIBLE", "name": "Свободный"}],
                "night_shifts": False,
                "professional_roles": [{"id": "40", "name": "Другое"}],
                "accept_incomplete_resumes": True,
                "experience": {"id": "between1And3", "name": "От 1 года до 3 лет"},
                "employment": {"id": "full", "name": "Полная занятость"},
                "employment_form": {"id": "FULL", "name": "Полная"},
                "internship": False,
                "adv_response_url": None,
                "is_adv_vacancy": False,
                "adv_context": None,
            },
            {
                "id": "110639788",
                "premium": False,
                "name": "Педагог по актерскому мастерству",
                "department": None,
                "has_test": False,
                "response_letter_required": False,
                "area": {"id": "1", "name": "Москва", "url": "https://api.hh.ru/areas/1"},
                "salary": None,
                "type": {"id": "open", "name": "Открытая"},
                "address": None,
                "response_url": None,
                "sort_point_distance": None,
                "published_at": "2025-01-28T14:22:32+0300",
                "created_at": "2025-01-28T14:22:32+0300",
                "archived": False,
                "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=110639788",
                "show_logo_in_search": None,
                "insider_interview": None,
                "url": "https://api.hh.ru/vacancies/110639788?host=hh.ru",
                "alternate_url": "https://hh.ru/vacancy/110639788",
                "relations": [],
                "employer": {
                    "id": "1696166",
                    "name": "Я - Актер! Детская театральная студия",
                    "url": "https://api.hh.ru/employers/1696166",
                    "alternate_url": "https://hh.ru/employer/1696166",
                    "logo_urls": {
                        "240": "https://img.hhcdn.ru/employer-logo/2228520.png",
                        "90": "https://img.hhcdn.ru/employer-logo/2228519.png",
                        "original": "https://img.hhcdn.ru/employer-logo-original/446638.png",
                    },
                    "vacancies_url": "https://api.hh.ru/vacancies?employer_id=1696166",
                    "accredited_it_employer": False,
                    "trusted": True,
                },
                "snippet": {
                    "requirement": "Безумно любить театр и мечтать разделить эту любовь с будущими звездами.",
                    "responsibility": None,
                },
                "contacts": None,
                "schedule": {"id": "fullDay", "name": "Полный день"},
                "working_days": [],
                "working_time_intervals": [
                    {"id": "from_four_to_six_hours_in_a_day", "name": "Можно сменами по 4-6 часов в день"}
                ],
                "working_time_modes": [],
                "accept_temporary": False,
                "fly_in_fly_out_duration": [],
                "work_format": [],
                "working_hours": [
                    {"id": "HOURS_4", "name": "4 часа"},
                    {"id": "HOURS_8", "name": "8 часов"},
                    {"id": "FLEXIBLE", "name": "По договорённости"},
                ],
                "work_schedule_by_days": [
                    {"id": "FIVE_ON_TWO_OFF", "name": "5/2"},
                    {"id": "WEEKEND", "name": "По выходным"},
                    {"id": "FLEXIBLE", "name": "Свободный"},
                ],
                "night_shifts": False,
                "professional_roles": [{"id": "132", "name": "Учитель, преподаватель, педагог"}],
                "accept_incomplete_resumes": True,
                "experience": {"id": "between1And3", "name": "От 1 года до 3 лет"},
                "employment": {"id": "part", "name": "Частичная занятость"},
                "employment_form": {"id": "PART", "name": "Частичная"},
                "internship": False,
                "adv_response_url": None,
                "is_adv_vacancy": False,
                "adv_context": None,
            },
            {
                "id": "112305768",
                "premium": False,
                "name": "Волшебник продаж",
                "department": None,
                "has_test": False,
                "response_letter_required": False,
                "area": {"id": "1", "name": "Москва", "url": "https://api.hh.ru/areas/1"},
                "salary": {"from": 300000, "to": None, "currency": "RUR", "gross": False},
                "type": {"id": "open", "name": "Открытая"},
                "address": {
                    "city": "Москва",
                    "street": "Профсоюзная улица",
                    "building": "56",
                    "lat": 55.670021,
                    "lng": 37.55248,
                    "description": None,
                    "raw": "Москва, Профсоюзная улица, 56",
                    "metro": {
                        "station_name": "Воронцовская",
                        "line_name": "Большая кольцевая линия",
                        "station_id": "97.816",
                        "line_id": "97",
                        "lat": 55.658333,
                        "lng": 37.540833,
                    },
                    "metro_stations": [
                        {
                            "station_name": "Воронцовская",
                            "line_name": "Большая кольцевая линия",
                            "station_id": "97.816",
                            "line_id": "97",
                            "lat": 55.658333,
                            "lng": 37.540833,
                        },
                        {
                            "station_name": "Новые Черемушки",
                            "line_name": "Калужско-Рижская",
                            "station_id": "6.92",
                            "line_id": "6",
                            "lat": 55.670077,
                            "lng": 37.554493,
                        },
                        {
                            "station_name": "Профсоюзная",
                            "line_name": "Калужско-Рижская",
                            "station_id": "6.121",
                            "line_id": "6",
                            "lat": 55.677671,
                            "lng": 37.562595,
                        },
                    ],
                    "id": "16501685",
                },
                "response_url": None,
                "sort_point_distance": None,
                "published_at": "2025-01-27T09:51:53+0300",
                "created_at": "2025-01-27T09:51:53+0300",
                "archived": False,
                "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=112305768",
                "show_logo_in_search": None,
                "insider_interview": None,
                "url": "https://api.hh.ru/vacancies/112305768?host=hh.ru",
                "alternate_url": "https://hh.ru/vacancy/112305768",
                "relations": [],
                "employer": {
                    "id": "11064781",
                    "name": "Мельник Евгений Владимирович",
                    "url": "https://api.hh.ru/employers/11064781",
                    "alternate_url": "https://hh.ru/employer/11064781",
                    "logo_urls": {
                        "240": "https://img.hhcdn.ru/employer-logo/6860507.png",
                        "90": "https://img.hhcdn.ru/employer-logo/6860506.png",
                        "original": "https://img.hhcdn.ru/employer-logo-original/1310062.png",
                    },
                    "vacancies_url": "https://api.hh.ru/vacancies?employer_id=11064781",
                    "accredited_it_employer": False,
                    "trusted": True,
                },
                "snippet": {
                    "requirement": "Коммуникабельность и умение находить подход к людям. Ответственность и ...",
                    "responsibility": None,
                },
                "contacts": None,
                "schedule": {"id": "fullDay", "name": "Полный день"},
                "working_days": [],
                "working_time_intervals": [],
                "working_time_modes": [],
                "accept_temporary": False,
                "fly_in_fly_out_duration": [],
                "work_format": [],
                "working_hours": [{"id": "HOURS_8", "name": "8 часов"}],
                "work_schedule_by_days": [{"id": "FIVE_ON_TWO_OFF", "name": "5/2"}],
                "night_shifts": False,
                "professional_roles": [{"id": "6", "name": "Агент по недвижимости"}],
                "accept_incomplete_resumes": True,
                "experience": {"id": "noExperience", "name": "Нет опыта"},
                "employment": {"id": "full", "name": "Полная занятость"},
                "employment_form": {"id": "FULL", "name": "Полная"},
                "internship": False,
                "adv_response_url": None,
                "is_adv_vacancy": False,
                "adv_context": None,
            },
        ],
        "found": 143,
        "pages": 48,
        "page": 0,
        "per_page": 3,
        "clusters": None,
        "arguments": None,
        "fixes": None,
        "suggests": None,
        "alternate_url": "https://hh.ru/search/vacancy?enable_snippets=True&items_on_page=3&"
                         "text=%D0%B2%D0%BE%D0%BB%D1%88%D0%B5%D0%B1%D0%BD%D0%B8%D0%BA",
    }
